### ISSUE TITLE
关于 “原项目声明了MIT协议，而本项目无需保留版权声明“ 的提醒

### ISSUE THREAD

**Issue by jexjws** [ZeroCatDev/ZeroCat#2]
并不是一个开源项目用了MIT协议你就不用 保留原项目版权声明 了，参考维基：[MIT许可证](https://zh.wikipedia.org/wiki/MIT許可證)。

实际上，MIT协议除了要求被许可人（在这里指的就是用原项目的你）在你的项目保留下原项目的MIT协议（ The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.），对被许可人并没有更多要求。

**Comment by SunWuyuan** [comment]
谢谢提醒，这句话更多指在分发过程中没有保留原项目的模棱两可的多许可证声明（商业使用联系qq），写的时候没写完整非常抱歉，协议内容将尽快补充
